<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<RotativaioPackageVersion Condition="'$(RotativaioPackageVersion)' == ''">1.6.3-beta</RotativaioPackageVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Rotativaio.AspNetCore" Version="$(RotativaioPackageVersion)" />
	</ItemGroup>

</Project>
